apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app:  server
    spec:
      containers:
      - name:  server
        image:  manikap123/pmsapp
        ports:
        - containerPort: 8087
        env:
          - name:  SPRING_DATASOURCE_USERNAME
            value: scott
          - name:  SPRING_DATASOURCE_PASSWORD
            value: tiger
          - name: SPRING_DATASOURCE_URL
            value: jdbc:postgresql://10.109.18.81:5432/postgres
